image: docker

services:
  - docker:dind

variables:
  GIT_STRATEGY: none

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache git
  - git clone https://github.com/EricssonResearch/oslc_prolog.git
  - cd oslc_prolog

build_image:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

deploy_to_swarm:
  stage: deploy
  script:
    - docker -H $SWARM_MANAGER login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker -H $SWARM_MANAGER stack deploy -c docker-compose.yml --with-registry-auth oslc_stack
  only:
    - master

deploy_to_swarm_erdc:
  stage: deploy
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker -H $SWARM_MANAGER_ERDC login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker -H $SWARM_MANAGER_ERDC stack deploy -c docker-compose.yml --with-registry-auth oslc_stack
  only:
    - master
  tags:
    - erdc